# Generated by Django 5.2.9 on 2026-01-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('bin_file', models.FileField(upload_to='firmware/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
