# Generated by Django 5.2.9 on 2026-01-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
