# Generated by Django 5.2.9 on 2026-01-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otaapp', '0002_firmware_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTALog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=50)),
                ('from_version', models.CharField(max_length=20)),
                ('to_version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=10)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
